In [1]:
import kagglehub
path = kagglehub.dataset_download("zahidmughal2343/video-games-sale")

print("Path to dataset files:", path)

100%|████████████████████████████████████████████████████████████████████████████████| 382k/382k [00:00<00:00, 891kB/s]

Extracting files...
Path to dataset files: C:\Users\boris\.cache\kagglehub\datasets\zahidmughal2343\video-games-sale\versions\1


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset = pd.read_csv ('C:\\Users\\boris\\.cache\\kagglehub\\datasets\\zahidmughal2343\\video-games-sale\\versions\\1\\video games sales.csv')
dataset.head()

Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [4]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
print ("Матрица признаков"); print(X)
print ("Зависимая переменная"); print(y)

Матрица признаков
[[1 'Wii Sports' 'Wii' ... 29.02 3.77 8.46]
 [2 'Super Mario Bros.' 'NES' ... 3.58 6.81 0.77]
 [3 'Mario Kart Wii' 'Wii' ... 12.88 3.79 3.31]
 ...
 [16598 'SCORE International Baja 1000: The Official Game' 'PS2' ... 0.0
  0.0 0.0]
 [16599 'Know How 2' 'DS' ... 0.01 0.0 0.0]
 [16600 'Spirits & Spells' 'GBA' ... 0.0 0.0 0.0]]
Зависимая переменная
[2006. 1985. 2008. ... 2008. 2010. 2003.]


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
imputer = imputer.fit(X[:, 1:3])
X_without_nan = X.copy()
X_without_nan[:, 1:3] = imputer.transform(X[:, 1:3])
X_without_nan

array([[1, 'Wii Sports', 'Wii', ..., 29.02, 3.77, 8.46],
       [2, 'Super Mario Bros.', 'NES', ..., 3.58, 6.81, 0.77],
       [3, 'Mario Kart Wii', 'Wii', ..., 12.88, 3.79, 3.31],
       ...,
       [16598, 'SCORE International Baja 1000: The Official Game', 'PS2',
        ..., 0.0, 0.0, 0.0],
       [16599, 'Know How 2', 'DS', ..., 0.01, 0.0, 0.0],
       [16600, 'Spirits & Spells', 'GBA', ..., 0.0, 0.0, 0.0]],
      shape=(16598, 10), dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
print("Зависимая переменная до обработки")
print(y)
y = labelencoder_y.fit_transform(y)
print("Зависимая переменная после обработки")
print(y)

Зависимая переменная до обработки
[2006. 1985. 2008. ... 2008. 2010. 2003.]
Зависимая переменная после обработки
[26  5 28 ... 28 30 23]


In [7]:
X_dirty = X.copy()
X_dirty

array([[1, 'Wii Sports', 'Wii', ..., 29.02, 3.77, 8.46],
       [2, 'Super Mario Bros.', 'NES', ..., 3.58, 6.81, 0.77],
       [3, 'Mario Kart Wii', 'Wii', ..., 12.88, 3.79, 3.31],
       ...,
       [16598, 'SCORE International Baja 1000: The Official Game', 'PS2',
        ..., 0.0, 0.0, 0.0],
       [16599, 'Know How 2', 'DS', ..., 0.01, 0.0, 0.0],
       [16600, 'Spirits & Spells', 'GBA', ..., 0.0, 0.0, 0.0]],
      shape=(16598, 10), dtype=object)

In [19]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Определяем трансформеры
transformers = [
    ('onehot', OneHotEncoder(sparse_output=False), [0]),  # sparse_output=False → dense
    ('imp', SimpleImputer(strategy='most_frequent'), [1, 2]) 
]

# Создаем ColumnTransformer
ct = ColumnTransformer(transformers)

# Применяем преобразования
X_transformed = ct.fit_transform(X_dirty)

print("Форма преобразованных данных:", X_transformed.shape)
print(X_transformed)

Форма преобразованных данных: (5, 4)
[[1.0 0.0 'A' 1]
 [0.0 1.0 'B' 2]
 [1.0 0.0 None 3]
 [0.0 1.0 'A' None]
 [1.0 0.0 'B' 1]]
